# Generated by Django 5.0.7 on 2024-07-16 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_remove_carinfo_price_carinfo_maxprice_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carinfo',
            name='energyType',
        ),
    ]
