# Generated by Django 5.0.7 on 2024-07-16 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_remove_carinfo_energytype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carinfo',
            name='createTime',
        ),
    ]
