# Generated by Django 5.0.7 on 2024-07-19 02:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_remove_carinfo_createtime'),
    ]

    operations = [
        migrations.AddField(
            model_name='carinfo',
            name='energyType',
            field=models.CharField(default=django.utils.timezone.now, max_length=50, verbose_name='能源类型'),
            preserve_default=False,
        ),
    ]
